name: Complete Build Example

on:
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        
      - name: bundle everything to zip
        run: zip -r code.zip ./
        
      - name: verification
        run: ls -alhR

      - run: npm install
      - run: npm run build --if-present

      - name: Run tests and generate coverage
        run: npm test -- --coverage

      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.7.0
        with:
          github-token: ${{ github.token }}
          coverage-file: ./coverage/clover.xml # Path to your clover, cobertura, jacoco, or lcov file
          working-directory: ./

